// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: links.sql

package database

import (
	"context"
)

const createShortLink = `-- name: CreateShortLink :exec
INSERT INTO links (short_link_blob, long_link) 
VALUES (?, ?)
`

type CreateShortLinkParams struct {
	ShortLinkBlob string
	LongLink      string
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) error {
	_, err := q.db.ExecContext(ctx, createShortLink, arg.ShortLinkBlob, arg.LongLink)
	return err
}

const getLinkByBlob = `-- name: GetLinkByBlob :one
SELECT id, short_link_blob, long_link, created_at FROM links WHERE short_link_blob = ?
`

func (q *Queries) GetLinkByBlob(ctx context.Context, shortLinkBlob string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByBlob, shortLinkBlob)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortLinkBlob,
		&i.LongLink,
		&i.CreatedAt,
	)
	return i, err
}
