// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"time"
)

type Link struct {
	ID            uint64
	ShortLinkBlob string
	LongLink      string
	CreatedAt     time.Time
}
